/**
 * `polder-drift profile` — scan the configured design system's source and generate
 * `.polder.profile.yml`: auto-derived tokens, class prefixes, prop signatures, and
 * sub-component maps that power the inline drift rules for in-house design systems.
 *
 * The output is a reviewable, committable file — generation never happens silently
 * at scan time. `.polder.yml` keys override entries in this file.
 */
import * as fs from 'fs';
import * as path from 'path';
import * as yaml from 'js-yaml';
import { resolveConfig, PROFILE_FILENAME } from '../resolve-config';
import { resolveDsSurface } from '../parser';
import { mergeCustomDetection, type CustomDetection } from '../profiles';
import { generateDetectionData } from '../generate-profile';

const HELP = `polder-drift profile — generate .polder.profile.yml from your design system's source

Scans each package in component_library (from node_modules, or the directory named
in library_paths) and derives:
  tokens           named hex color constants (generic grays excluded)
  class_prefixes   repeated BEM-style class prefixes (acme--…)
  prop_signatures  distinctive component prop combinations
  sub_components   compound components (CardHeader → Card)
  name_segments    confidence-boost words for sub-component matches

The result is written to ${PROFILE_FILENAME} for you to REVIEW, EDIT, and COMMIT.
Every entry can create findings on PRs — delete anything that looks generic.
Keys in .polder.yml override entries in this file.

Usage:
  polder-drift profile [options]

Options:
  --cwd <dir>       Working directory / repo root (default: process.cwd()).
  --config <path>   Path to .polder.yml (default: <cwd>/.polder.yml).
  --force           Overwrite an existing ${PROFILE_FILENAME}.
  -h, --help        Show this help.

Exit codes:
  0  profile written
  1  refused (file exists without --force, or nothing distinctive was found)
  2  configuration or usage error
`;

interface ProfileOptions {
  cwd: string;
  configPath: string;
  force: boolean;
  help: boolean;
}

function parseProfileArgs(argv: string[]): ProfileOptions {
  const opts: ProfileOptions = { cwd: process.cwd(), configPath: '', force: false, help: false };
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    switch (arg) {
      case '-h':
      case '--help':
        opts.help = true;
        break;
      case '--force':
        opts.force = true;
        break;
      case '--cwd':
        opts.cwd = argv[++i] ?? '';
        if (!opts.cwd) throw new Error('--cwd requires a path');
        break;
      case '--config':
        opts.configPath = argv[++i] ?? '';
        if (!opts.configPath) throw new Error('--config requires a path');
        break;
      default:
        throw new Error(`unknown option: ${arg}`);
    }
  }
  if (!opts.configPath) opts.configPath = path.join(opts.cwd, '.polder.yml');
  return opts;
}

/** YAML-serialise only the keys present, in snake_case, sorted for stable diffs. */
function renderProfileYaml(data: CustomDetection, packages: string[]): string {
  const body: Record<string, unknown> = {};
  if (data.tokens) body.tokens = data.tokens;
  if (data.classPrefixes) body.class_prefixes = data.classPrefixes;
  if (data.propSignatures) body.prop_signatures = data.propSignatures;
  if (data.subComponents) body.sub_components = data.subComponents;
  if (data.nameSegments) body.name_segments = data.nameSegments;

  const header =
    `# Generated by \`polder-drift profile\` from: ${packages.join(', ')}\n` +
    `# REVIEW BEFORE COMMITTING — every entry here can create findings on PRs.\n` +
    `# Edit freely (deletions are respected until you regenerate with --force).\n` +
    `# Keys in .polder.yml override entries in this file.\n`;
  return header + yaml.dump(body, { sortKeys: true, lineWidth: 100 });
}

export function runProfileSubcommand(argv: string[]): number {
  let opts: ProfileOptions;
  try {
    opts = parseProfileArgs(argv);
  } catch (err) {
    process.stderr.write(`polder-drift: ${(err as Error).message}\n\n${HELP}`);
    return 2;
  }
  if (opts.help) {
    process.stdout.write(HELP);
    return 0;
  }

  let resolved;
  try {
    resolved = resolveConfig(opts.cwd, opts.configPath);
  } catch (err) {
    process.stderr.write(`polder-drift: invalid config — ${(err as Error).message}\n`);
    return 2;
  }
  if (!resolved) {
    process.stderr.write(
      `polder-drift profile: no .polder.yml at ${opts.configPath} and could not auto-detect ` +
        `a design system. Run \`polder-drift init\` first.\n`,
    );
    return 2;
  }
  const config = resolved.config;

  const target = path.join(opts.cwd, PROFILE_FILENAME);
  if (fs.existsSync(target) && !opts.force) {
    process.stderr.write(
      `polder-drift profile: ${PROFILE_FILENAME} already exists; leaving it untouched ` +
        `(it may contain hand edits). Re-run with --force to overwrite.\n`,
    );
    return 1;
  }

  let data: CustomDetection = {};
  const scanned: string[] = [];
  for (const pkg of config.componentLibrary) {
    const libraryPath = config.libraryPaths?.[pkg];
    // Prefer the repo checkout when configured — it has real source; node_modules
    // may only carry built output.
    const pkgDir = libraryPath
      ? path.resolve(opts.cwd, libraryPath)
      : path.join(opts.cwd, 'node_modules', pkg);
    if (!fs.existsSync(pkgDir)) {
      process.stderr.write(
        `polder-drift profile: "${pkg}" not found at ${pkgDir} — skipping. ` +
          `Install it, or point library_paths."${pkg}" at its repo.\n`,
      );
      continue;
    }
    const dsExports = resolveDsSurface(pkg, opts.cwd, libraryPath);
    if (dsExports.size === 0) {
      process.stderr.write(
        `polder-drift profile: could not resolve any exports for "${pkg}" — skipping.\n`,
      );
      continue;
    }
    const generated = generateDetectionData(pkgDir, dsExports);
    data = mergeCustomDetection(data, generated.data);
    scanned.push(pkg);
    process.stderr.write(
      `polder-drift profile: ${pkg} — ${generated.stats.filesScanned} file(s), ` +
        `${generated.stats.signatures} prop signature(s), ${generated.stats.tokens} token(s), ` +
        `${generated.stats.subComponents} sub-component(s), ${generated.stats.classPrefixes} class prefix(es).\n`,
    );
  }

  if (scanned.length === 0 || Object.keys(data).length === 0) {
    process.stderr.write(
      'polder-drift profile: nothing distinctive found — no file written. The export-based ' +
        'rules (import-drift, local-shadow) work without a profile; you can also add the ' +
        'detection keys to .polder.yml by hand.\n',
    );
    return 1;
  }

  fs.writeFileSync(target, renderProfileYaml(data, scanned));
  process.stdout.write(
    `polder-drift profile: wrote ${PROFILE_FILENAME}. Review it, prune anything generic, ` +
      `and commit — scan and the PR comment pick it up automatically.\n`,
  );
  return 0;
}
